const components = {
  "AdminDashboard": "AppComponents",
  "AppShell": "AppComponents",
  "FinancialSimulator": "AppComponents",
  "PublicMenu": "AppComponents",
  "AppModal": "Visual",
  "Button": "Visual",
  "CartDrawer": "Visual",
  "CategoryCarousel": "Visual",
  "ComboCard": "Visual",
  "CurrencySwitcher": "Visual",
  "Input": "Visual",
  "Link": "Visual",
  "Loading": "Visual",
  "MultiRoute": "Visual",
  "Navbar": "Visual",
  "NotFound": "Visual",
  "PlatoCard": "Visual",
  "Route": "Visual",
  "SearchBar": "Visual",
  "Sidebar": "Visual",
  "ThemeToggle": "Visual",
  "ApiService": "Service",
  "CartService": "Service",
  "ExchangeService": "Service",
  "FetchManager": "Service",
  "IndexedDbManager": "Service",
  "LocalStorageManager": "Service",
  "RestaurantStore": "Service"
};

export default components;
